name       : python-pefile
version    : 2023.2.7
release    : 1
source     :
    - https://github.com/erocarrera/pefile/archive/refs/tags/v2023.2.7.tar.gz : 0748ae46a3b93c5d393620c827874266c86ac81f52bf25fc08e7e95efff9e8f0
license    : MIT
component  : programming.python
summary    : A Python module to read and work with PE (Portable Executable) files
description: |
    pefile is a multi-platform Python module to parse and work with Portable Executable (PE) files. Most of the information contained in the PE file headers is accessible, as well as all the sections' details and data.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
